### ISSUE TITLE
Plugin does not work on 6.99

### ISSUE THREAD

**Issue by AiGreek** [reilly-callaway/Ki-Fillet#10]
Hi, 

I wanted to test this plugin for curiosity, to bad it doesn't work on the latest Nightly version of Kicad. :-(

![image](https://user-images.githubusercontent.com/16197044/174452117-64b5d16e-0735-4f73-bbea-f962798f7d4b.png)

```
Application: KiCad (64-bit)

Version: (6.99.0-2176-g69f25f35a8), release build

Libraries:
	wxWidgets 3.1.7
	FreeType 2.11.1
	HarfBuzz 4.2.0
	FontConfig 2.14.0
	libcurl/7.83.1-DEV Schannel zlib/1.2.12

Platform: Windows 11 (build 22000), 64-bit edition, 64 bit, Little endian, wxMSW

Build Info:
	Date: Jun 17 2022 07:52:05
	wxWidgets: 3.1.7 (wchar_t,wx containers)
	Boost: 1.79.0
	OCC: 7.6.0
	Curl: 7.83.1-DEV
	ngspice: 37
	Compiler: Visual C++ 1929 without C++ ABI

Build settings:
	KICAD_USE_OCC=ON
	KICAD_SPICE=ON
```

**Comment by reilly-callaway** [comment]
Thanks for checking the plugin out and the heads up on nightly. Nightly has an unstable and everchanging API so it won't be supported until KiCad V7 gets much closer to release.
